### API's


###root api
GET http://localhost:8000/

### register customer
POST http://localhost:8000/api/v1/customer/
Content-Type: application/json

{
 "username":"kishor",
 "password":"kjabs123",
 "email":"k@gmail.com"
}